# --- DATABASE CONFIGURATION ---
spring.datasource.url=jdbc:postgresql://localhost:5432/limo_market
spring.datasource.username=conellimo
spring.datasource.password=devpass123
spring.datasource.driver-class-name=org.postgresql.Driver
  
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database=postgresql
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
  
  # --- FILE UPLOAD LIMITS ---
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
  
  # --- TEMPORARY SECURITY 
spring.security.user.name=admin
spring.security.user.password=1234